
### REGISTER
POST http://localhost:4000/api/auth/register
Content-type: application/json

{
    "name" : "PruebaTrainer",
    "email" : "pruebatrainer@gmail.com",
    "password" : "trainer12345",
    "role" : "TRAINER",
    "daysOfWeek" : [1, 2, 3, 4, 5],
    "startTime" :  540,
    "endTime" : 1020
}


### LOGIN
POST http://localhost:4000/api/auth/login
Content-type: application/json

{
    "email" : "pruebatrainer@gmail.com",
    "password" : "trainer12345"
}


### DELETE
DELETE http://localhost:4000/api/user/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoicHJ1ZWJhdHJhaW5lckBnbWFpbC5jb20iLCJyb2xlIjoiVFJBSU5FUiIsImlhdCI6MTc1MzM2MTIwNywiZXhwIjoxNzUzOTY2MDA3fQ.tMsGr7IsXTt8yqs5669BYFmnJaCbpoWra_WaXn3P3D8